### ISSUE TITLE
'Active' not calculated correctly

### ISSUE THREAD

**Issue by diedummydie** [sagarkarira/coronavirus-tracker-cli#1]
Active should subtract Recovered and Deaths from Confirmed, but it just repeats the figure for Confirmed.

![Screen Shot 2020-03-15 at 6 41 03 PM](https://user-images.githubusercontent.com/1759544/76712236-1727fb80-66ed-11ea-882c-fe84867786e2.png)

**Comment by diedummydie** [comment]
note — 'Active' category is calculated correctly for the first row.

**Comment by sagarkarira** [comment]
Fix https://github.com/sagarkarira/coronavirus-tracker-cli/commit/9c99ebe1faf2aa58d1ececfada4ab71f2914b978
