### ISSUE TITLE
More frequent updates request

### ISSUE THREAD

**Issue by LesnyRumcajs** [sagarkarira/coronavirus-tracker-cli#10]
Perhaps hourly / every two hours? So far it's the best tool out there except for the severely outdated information.

**Comment by sagarkarira** [comment]
Thanks @LesnyRumcajs 

I will try and see what can be done. But John Hopkins data is updated every 24 hours.  You can check it out [here](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data)

**Comment by LesnyRumcajs** [comment]
Ah, I thought there are more sources and / or the data source is updated more often. Makes more sense now. Thanks!

**Comment by sagarkarira** [comment]
@LesnyRumcajs I will be adding the latest news/updates command today. That will help with the discrepancy.

**Comment by Empty2k12** [comment]
Something that is updated more often is https://www.worldometers.info/coronavirus/ but I'm not sure you can use their data.

**Comment by sagarkarira** [comment]
@Empty2k12 They dont have an official API, sadly. I am looking for a realtime tracking API, especially because the new cases are coming up so fast. 😢

**Comment by LesnyRumcajs** [comment]
This page https://covid-19-sars.pl/ uses some allegedly WHO data from: https://coronavirus-19-api.herokuapp.com (which is supposed to be on par with worldometers).

**Comment by sagarkarira** [comment]
@LesnyRumcajs API looks good. I will try to integrate it tomorrow.

**Comment by sagarkarira** [comment]
Added a secondary API realtime updates. https://github.com/sagarkarira/coronavirus-tracker-cli/pull/60

[https://corona-stats.online/?source=2](https://corona-stats.online/?source=2)

**Comment by LesnyRumcajs** [comment]
Great, thank you!
