### ISSUE TITLE
curl https://corona-stats.online/US no longer shows individual states

### ISSUE THREAD

**Issue by HirschBerge** [sagarkarira/coronavirus-tracker-cli#101]
I used to be able to curl to a file and grep the states to put in my bar, but it no longer shows the states, just total US. Thanks

**Comment by kcallis** [comment]
Same issue as well

**Comment by onzyone** [comment]
the default source is pointing to a source that doesn't show individual provinces ...

You can get the info by running like this `curl 'https://corona-stats.online/CA?source=1'`

**Comment by HirschBerge** [comment]
This is something I've tried before, It does work with Canada (which I obviously had not tried), but it doesn't work with the US. it just brings up the overall US, not any of the states.

**Comment by mock** [comment]
Will the state data return in some different format?

**Comment by sagarkarira** [comment]
Sorry, I was a busy past week. But I've added US state-wise stats here: 
[https://corona-stats.online/states/us](https://corona-stats.online/states/us)

I will be adding other countries' state-wise API too. If you know sources please do share.

**Comment by HirschBerge** [comment]
Thank you
