### ISSUE TITLE
Can't access to site: result.data.reduce is not a function

### ISSUE THREAD

**Issue by sbruselario** [sagarkarira/coronavirus-tracker-cli#110]
URL: https://corona-stats.online/

Response:
    I am sorry. Something went wrong. Please report it

    result.data.reduce is not a function
    

Stay safe. Stay inside.
Code: https://github.com/sagarkarira/coronavirus-tracker-cli
Twitter: https://twitter.com/ekrysis

Last Updated on: 16-Apr-2020 23:04 UTC

US STATES API: https://corona-stats.online/states/us
HELP: https://corona-stats.online/help
SPONSORED BY: ZEIT NOW

**Comment by sagarkarira** [comment]
Thanks for reporting. 
I fixed it.
