### ISSUE TITLE
data massively wrong

### ISSUE THREAD

**Issue by eastein** [sagarkarira/coronavirus-tracker-cli#118]
New cases in the USA is 1,694 and in the world, 59,791 according to https://corona-stats.online/US right now. This is so wrong its not even funny. Fix your code or take down the website.

**Comment by sagarkarira** [comment]
@eastein The data is scraped from https://www.worldometers.info/coronavirus/#countries. It will exactly match it. New cases are correct as shown in worldometer as well as this site.

> This is so wrong its not even funny. Fix your code or take down the website.

You can be a little more constructive with the feedback and comment. The mention of this statement absolutely unnecessary. It's a free service that can be used by anybody. The code is open source so anyone can fork and make improvements.

**Comment by eastein** [comment]
I suppose I could be nicer, sorry for saying its not funny, but waiting for patches with the site up passing out wrong data is not good either.

**Comment by eastein** [comment]
data is still wrong. When I reload https://corona-stats.online/US repeatedly it bounces back and forth between 68,680 and 58,102. I don't know what the right numbers are today but it should at least be consistent.
