### ISSUE TITLE
Add last_updated information

### ISSUE THREAD

**Issue by drego85** [sagarkarira/coronavirus-tracker-cli#12]
Hello,
thank's for your job. 

I think it is useful to indicate the date and time of the last update of the data.

Your source reports this information in the "last_updated" field, it would be enough to report it in the output.

Thanks

**Comment by sagarkarira** [comment]
Done. https://github.com/sagarkarira/coronavirus-tracker-cli/commit/6de7019e9a2100c01bf809165db4b7f6785d66e4
