### ISSUE TITLE
Palestine showing incorrect data.

### ISSUE THREAD

**Issue by jeff-aronow** [sagarkarira/coronavirus-tracker-cli#15]
![image](https://user-images.githubusercontent.com/26280681/76845123-4007d800-6836-11ea-92e8-080691f0d3b2.png)
For some reason, Palestine is showing as 0, but I believe they have like 37 cases as of this morning 3/17 10:00 GMT.

Also, seriously?
"occupied Palestinian territory (PS)"

**Comment by sagarkarira** [comment]
@jeff-aronow Sorry for that. But my tracker is just using the data from [John Hopkins Univeristy](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data). They update it every 24 hours.

 Also, I am just listing the countries as provided by them.  You can create an issue there: 

https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data
