### ISSUE TITLE
Emoji break alignment in terminals that double space emoji

### ISSUE THREAD

**Issue by diedummydie** [sagarkarira/coronavirus-tracker-cli#2]
Please consider adding an option to omit the emoji.

![Screen Shot 2020-03-15 at 6 41 03 PM](https://user-images.githubusercontent.com/1759544/76712263-6a9a4980-66ed-11ea-86cf-a37f7dfc9e36.png)

**Comment by sagarkarira** [comment]
Thanks, @diedummydie.
I have removed emojis for now. I will add optional param.

**Comment by diedummydie** [comment]
Looks good, thank you for responding and for creating this tool.  

FYI, for the deltas there are also the unicode characters ▲ and ▼ which are always single-wide, from the [geometric shapes](https://en.wikipedia.org/wiki/Geometric_Shapes) block.

**Comment by alexanderadam** [comment]
It's still broken for me:

![Screenshot_20200316_140803](https://user-images.githubusercontent.com/372620/76761359-95d57500-678f-11ea-9e7d-ea31a2aefcd2.png)

**Comment by sagarkarira** [comment]
I've removed all the emojis for now. I thought only the flag emojis are causing the problem. I think I will add an optional param because emojis are ❤️

**Comment by jeffbabuyo** [comment]
No color?

![image](https://user-images.githubusercontent.com/48270144/76823814-46a34900-6850-11ea-8b95-758a7e7824b5.png)

**Comment by sagarkarira** [comment]
@jeffbabuyo Sadly curl request supports no color. As this project is hosted on Zeit Now and they are striping away ANSI codes. I have looked into it and found no solutions so far.

What you could do is install the global package from npm then run the command `corona`. 
Check readme.

**Comment by sagarkarira** [comment]
Closing this issue as emojis are added back with optional param. 
```corona --emojis```
https://github.com/sagarkarira/coronavirus-tracker-cli/pull/19
