### ISSUE TITLE
[bug] json: deathsByDay and recoveredByDay are identical

### ISSUE THREAD

**Issue by skeld** [sagarkarira/coronavirus-tracker-cli#20]
When parsing the json format (https://corona-stats.online/?format=json), it appears that the deathsByDay and recoveredByDay are identical values.
Tested for France and China, using R and jsonlite.

**Comment by sagarkarira** [comment]
Thanks, @skeld. 

Pushed a fix https://github.com/sagarkarira/coronavirus-tracker-cli/commit/1a975431b37e068d7a6ce3f8ec0ba0678dba6e20
