### ISSUE TITLE
Render HTML when user-agent is not curl.

### ISSUE THREAD

**Issue by sagarkarira** [sagarkarira/coronavirus-tracker-cli#21]
I am seeing a lot of requests coming from web browsers. 

Sadly I am sending ASCII table which is meant for terminal and is not rendered properly in the browser. 

I think creating a simple minimalistic Html table will do the job for these users. 

I will pick this up on weekend but if anyone is interested, just let me know.

**Comment by archcorsair** [comment]
I can work on this

**Comment by sagarkarira** [comment]
Thanks, @archcorsair . 👍  Feel free to ask anything.

**Comment by archcorsair** [comment]
I noticed in #14 you mentioned that you did not want to respond with plain text.

I am thinking on checking if the request did not originate from a curl user agent then we can return HTML from an HTML template we can populate with the table data. This will require building out a row/column builder manually. If you have any better ideas I'm open to hearing them. If there's an existing package that may help with this and you're open to using it, we can do that too.

**Comment by archcorsair** [comment]
I've written a very simple HTML table builder and the WIP result, unstyled, looks like this:
![image](https://user-images.githubusercontent.com/1036921/77019083-f0600400-693c-11ea-8fbe-9ad17fc5e96d.png)

**Comment by iamsugam** [comment]
While the website https://corona-stats.online/ shows an unmanaged table on browser, viewing the source i.e. view-source:https://corona-stats.online/ will show readable table for the visitor on browser.

**Comment by hackakshay** [comment]
how are you getting updates on data please let me know 
and yeah i can help you with this

**Comment by sagarkarira** [comment]
@iamsugam @archcorsair The issue was with the font. It is not being rendered properly and the table boxes are breaking because the default font is not monospace. I set my browser font to Monaco and it worked. ✌️ 

![Screen Shot 2020-03-19 at 1 44 19 PM](https://user-images.githubusercontent.com/4711084/77046364-da0f8200-69e8-11ea-8dd3-e18369844ae4.png)


On the local server color, ANSI code are not stripped but where its hosted on Zeit it automatically removing ANSI, that is why we can't see colors when we curl.

I think this content inside a <pre> tag and setting an explicit font like `Roboto Mono` will do the job. With a black background similar to [wttr](http://wttr.in/)

What do you think?

**Comment by sagarkarira** [comment]
@archcorsair Thanks for the PR. I think this template works for now. I can revisit this later for more improvements. 
https://github.com/sagarkarira/coronavirus-tracker-cli/pull/28
Closing this for now.

**Comment by loop36** [comment]
How about SPA?using Angular tables?
