### ISSUE TITLE
Filter by country not working

### ISSUE THREAD

**Issue by atharvaj77** [sagarkarira/coronavirus-tracker-cli#25]
after running command corona 'country name', it shows the entire table without filtering out country specific info. I think there is problem with bycountry.js

**Comment by ssiyad** [comment]
Can you please post the exact command you used?

**Comment by atharvaj77** [comment]
I used the command `corona India`, which returned me the entire table
![Screenshot from 2020-03-19 13-45-53](https://user-images.githubusercontent.com/58818674/77045839-fced6680-69e7-11ea-92fc-bb79a32bb47f.png)

**Comment by sagarkarira** [comment]
@atharvaj77 I think you might have an old version. 

Just do corona `corona --version` if it is less than 0.4.0 then you need to update using `npm-update`

**Comment by atharvaj77** [comment]
Thanks it worked!
