### ISSUE TITLE
Add some small css rule to <body>

### ISSUE THREAD

**Issue by racztiborzoltan** [sagarkarira/coronavirus-tracker-cli#27]
Just a tip: 

Please add the following CSS rules to the <body> in browser for a better look in browsers!

```
font-family: monospace;
white-space: pre;
```

**Comment by sagarkarira** [comment]
Thanks @racztiborzoltan , we have that discussion going on here: https://github.com/sagarkarira/coronavirus-tracker-cli/issues/21

**Comment by racztiborzoltan** [comment]
Ok! All right!
