### ISSUE TITLE
Remove Spaces in names

### ISSUE THREAD

**Issue by matt-horwood-mayden** [sagarkarira/coronavirus-tracker-cli#3]
Thanks for this tool, but could you please remove spaces from country names?

E.G. United Kingdom -> could be United_Kingdom or UK

**Comment by Iamnome** [comment]
It is annoying but %20 in place of the space works for now.

**Comment by sagarkarira** [comment]
I've fixed this by adding country code as params.
You can try using 

`curl https://corona-stats.online/UK`
or
`curl https://corona-stats.online/GB`
