### ISSUE TITLE
Cannot get world wide data via JSON

### ISSUE THREAD

**Issue by CWempe** [sagarkarira/coronavirus-tracker-cli#34]
Maybe I am doing something wrong.

But when I fetch the following URL, I do not the total world wide data.

https://corona-stats.online/?format=json

The first Entry in the JSON list is China.

Without `?format=json` it looks god.

**Comment by sagarkarira** [comment]
In the case of China, US, Canada, UK etc the data is grouped `province` so you need to aggregate it to get the total data.

**Comment by CWempe** [comment]
I know.
But I don't care about thos.

I was expecting "World" to be the first element of the JSON.
Or do I have to summ all elements to get the total number?

**Comment by sagarkarira** [comment]
@CWempe Oh, I will add this in some time.

**Comment by sagarkarira** [comment]
@CWempe Check now. I have added the field. Search `World`.
https://github.com/sagarkarira/coronavirus-tracker-cli/commit/a6e12a51c175b7ebca34ed3affe04108468bfb06

**Comment by CWempe** [comment]
Works as expected..
Thanks 👍
