### ISSUE TITLE
Colors not appearing on curl request.

### ISSUE THREAD

**Issue by sagarkarira** [sagarkarira/coronavirus-tracker-cli#43]
When you run the express server locally, you get colors because I am not stripping ANSI codes. But when you deploy to Zeit now, colors are not coming. Maybe because they are stripping ANSI codes. 

I am not able to figure this out. If anyone has any idea please let me know.

**Comment by XhmikosR** [comment]
@styfle: do you have any ideas maybe? :)

**Comment by styfle** [comment]
Correct, when you visit `deployment.now.sh/_logs`  the logs don't include colors.

You might want to try Log Drains if you need more advanced logging https://zeit.co/blog/log-drains

**Comment by XhmikosR** [comment]
@styfle I think @sagarkarira refers to using `curl https://corona-stats.online/` as opposed to running it locally like `curl locahost:3001`

**Comment by styfle** [comment]
Oh I understand now.

Try setting `FORCE_COLOR=1` to force chalk to set colors even without TTY.

**Comment by styfle** [comment]
I created PR #51 but you don't have this repo linked so it didn't autodeploy.

Can you try signing up https://zeit.co/github

**Comment by sagarkarira** [comment]
@styfle It worked. ❤️ 
I've also integrated my repo with Zeit. 

Check here: `curl https://coronavirus-tracker.sagark.now.sh`

Merging this PR.

**Comment by sagarkarira** [comment]
@styfle I didn't know about Git integration. This is awesome.

**Comment by styfle** [comment]
@sagarkarira I highly recommend the Git Integration because then ZEIT Now will deploy each PR and you can try out the preview url before merging to master which will perform the production deployment.

https://twitter.com/rauchg/status/1240031831090532353

**Comment by XhmikosR** [comment]
BTW do you have any idea why the slowdown? This wasn't present a couple of says ago @sagarkarira https://gtmetrix.com/compare/G9zeIBok/INyNUd35#waterfall

**Comment by sagarkarira** [comment]
Maybe it's because of the API I am using to fetch the data. I have added node-cache around the response, but I don't really know that Zeit allows variable caching as it is serverless. 

The caching works locally but I haven't added logs to test in zeit dev or prod. I thought it would work. If the request is going to that API on each call then the response will be slow.

Also, I have removed Zeit smart CDN caching because there was a bug which was returning HTML is case of curl request. 

But changing the `Cache-Control` to `no-cache` didn't solve it.
The issue was with the regex which was pushed sometime earlier. Check [here](https://stackoverflow.com/questions/1520800/why-does-a-regexp-with-global-flag-give-wrong-results). I've removed the global flag and will push the code now.

**Comment by sagarkarira** [comment]
I will check if variable caching works on zeit by adding some logs and will let you know

**Comment by XhmikosR** [comment]
I'm not familiar with this, I'm not sure how to solve it, but we should have CDN and caching for sure as you can see :/

**Comment by styfle** [comment]
You should add `s-maxage` if you want to take advantage of the Smart CDN.

https://zeit.co/docs/v2/network/caching
