### ISSUE TITLE
Remove HTML code when called from curl

### ISSUE THREAD

**Issue by Jiab77** [sagarkarira/coronavirus-tracker-cli#53]
Hello,
I really love your project but the recent changes made it unuable with `curl`.

Is it possible to remove the `HTML` when call from `curl`? Is can be done easily by reading the `user-agent` header.

Thanks for your work.

**Comment by sagarkarira** [comment]
@Jiab77 This is happening due to caching. Working on this.

**Comment by Jiab77** [comment]
Thanks for this quick reply @sagarkarira ! I understand so let's keep this issue open till it's not fixed.

**Comment by sagarkarira** [comment]
Closing this, it was fixed here: https://github.com/sagarkarira/coronavirus-tracker-cli/commit/a921f609026dc9bc58796cd33ecf3eb2cf4d1268

**Comment by Jiab77** [comment]
Thank you so much!

I can reuse it with `curl` and `watch` that way:

```bash
watch -n 600 "curl -Ss https://corona-stats.online/<country>"
```

> Just add `-c` to handle `ANSI` color escape squences.
>
> _Useful for doing same with https://corona-stats.online/updates_

Feel free to add that to your README. :wink:
