### ISSUE TITLE
Add census data for total population

### ISSUE THREAD

**Issue by Tampa** [sagarkarira/coronavirus-tracker-cli#56]
Pretty much as the title says knowing the actual number of people within a country to compare to infection numbers to gauge overall spread within a country. This data should be available through sources such as wikipedia or the official government pages of the respective countries.

**Comment by sagarkarira** [comment]
I have added a new API from a secondary source which is updated more frequently (every hour). It has a column `Cases per million` 

Check here: `curl https://corona-stats.online?source=2`

**Comment by sagarkarira** [comment]
^Closing this.
