### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by XhmikosR** [sagarkarira/coronavirus-tracker-cli#6]
Hey, there @sagarkarira, thanks for this!

It appears this doesn't work at all on Windows 10 native cmd. Not sure how hard this would be, I thought I'd report it :)

![Annotation 2020-03-16 170812](https://user-images.githubusercontent.com/349621/76771986-d55c8b00-67a8-11ea-892b-1b3db1e5e459.png)

**Comment by CyberDracula** [comment]
what `curl` version do you use?

**Comment by XhmikosR** [comment]
Sorry, forgot to mention the curl version :/

It happens with Windows own curl and the latest curl version, so both of these:

```
C:\Users\xmr\Desktop>C:\Windows\System32\curl.exe --version
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

C:\Users\xmr\Desktop>curl --version
curl 7.69.1 (x86_64-pc-win32) libcurl/7.69.1 OpenSSL/1.1.1d (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.9.0 nghttp2/1.40.0
Release-Date: 2020-03-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP brotli libz
```

**Comment by CyberDracula** [comment]
Update to anything above 7.62.0. There is an UTF-8 bug in your version:

[https://github.com/curl/curl/issues/3008](url)

**Comment by XhmikosR** [comment]
Like I said, I do use 7.69, same issue. It's unrelated to the curl version. It's due to Windows not supporting those UTF characters.

**Comment by CyberDracula** [comment]
![OK](https://user-images.githubusercontent.com/1976475/76847917-7dc32b80-684b-11ea-8fca-d35a295e2e97.png)
works ok for me with 7.69.1

**Comment by XhmikosR** [comment]
That's really weird, thanks for the hint.

I indeed can reproduce this, so I will close the issue.
