### ISSUE TITLE
Mortality vs CFR

### ISSUE THREAD

**Issue by JayVii** [sagarkarira/coronavirus-tracker-cli#61]
The table lists "Mortality %", while I suspect it actually means Case Fatality Rate (CFR):

[From Wikipedia](https://en.wikipedia.org/wiki/Mortality_rate):
> Mortality rate, or death rate, is a measure of the number of deaths (in general, or due to a specific cause) in a particular population, scaled to the size of that population, per unit of time. Mortality rate is typically expressed in units of deaths per 1,000 individuals per year; thus, a mortality rate of 9.5 (out of 1,000) in a population of 1,000 would mean 9.5 deaths per year in that entire population, or 0.95% out of the total. It is distinct from "morbidity", which is either the prevalence or incidence of a disease, and also from the incidence rate (the number of newly appearing cases of the disease per unit of time).

[From Wikipedia](https://en.wikipedia.org/wiki/Case_fatality_rate):
> In epidemiology, a case fatality rate (CFR) — sometimes called case fatality risk or case fatality ratio — is the proportion of deaths from a certain disease compared to the total number of people diagnosed with the disease for a certain period of time.

Therefore, "mortality" sets the deaths in perspective to entire population of a given region/country **after** the fact or within a certain time frame, while the CFR sets the **current deaths** in perspective to some affected case numbers (diseased people).

**Comment by sagarkarira** [comment]
I will change it to CFR.

**Comment by sagarkarira** [comment]
Fixed went live in this. https://github.com/sagarkarira/coronavirus-tracker-cli/pull/72
