### ISSUE TITLE
'?source=2&format=json' not working as expected

### ISSUE THREAD

**Issue by CWempe** [sagarkarira/coronavirus-tracker-cli#62]
<https://corona-stats.online/?source=2&format=json> shows the green/black website instead of the raw json text.

**Comment by sagarkarira** [comment]
I am working on it. Will push in some time.

**Comment by sagarkarira** [comment]
This is live now.

**Comment by CWempe** [comment]
I think the format changed a little, but I got it working.

Thanks.
