### ISSUE TITLE
Country code does not match anything in the database.

### ISSUE THREAD

**Issue by LordSushiPhoenix** [sagarkarira/coronavirus-tracker-cli#64]
Trying to request a specific country returns the error:

 "I am sorry. Something went wrong. Please report it 
Country code CA does not match anything in the database. "

Viewing all countries seems to have no data.
![image](https://user-images.githubusercontent.com/19640845/77239829-548cfd00-6bb5-11ea-80d0-27f1230557de.png)

**Comment by WindedDragon** [comment]
I'm also having this issue when trying to lookup Canada specifically.

**Comment by sagarkarira** [comment]
Strange,
These are working : 

[https://corona-stats.online/ca?source=2](https://corona-stats.online/ca?source=2)

[https://corona-stats.online/CA](https://corona-stats.online/CA)

Can you try these?

**Comment by LordSushiPhoenix** [comment]
They work, as well as the links I was initially having problems with. I'll close the issue.
