### ISSUE TITLE
Data not updated with most recent.

### ISSUE THREAD

**Issue by eabase** [sagarkarira/coronavirus-tracker-cli#71]
**Where are your data sources taken from?**

For several countries, the data is not up to date with this tool, as it is on their official sites. 
Please explain how to fix this.

E.g. For Lithuania:
```
$ curl https://corona-stats.online/Lithuania?minimal=true

Rank      State Confirmed  Recovered Deaths Active Mortality % Recovered % 1 Day ▲ 1 Week ▲
Lithuania Total         83         1      1     81        1.20        1.20    34 ▲     75 ▲
```

Versus: 
* https://infogram.com/lietuviskas-live-koronaviruso-skaiciavimas-1hnp27y0vyjy2gq
* https://www.delfi.lt/media/corona-data/lithuania.php

---

![brave_2020-03-22_15-37-19](https://user-images.githubusercontent.com/52289379/77250833-265dfa80-6c53-11ea-896f-95e23b2a239c.png)

```
{"lietuva":{"region":"Lietuva","confirmed":105,"recovered":1,"deaths":1},"alytus":
{"region":"Alytus","confirmed":0,"recovered":0,"deaths":0},"kaunas":
{"region":"Kaunas","confirmed":18,"recovered":0,"deaths":0},"klaipeda":
{"region":"Klaip\u0117da","confirmed":18,"recovered":0,"deaths":0},"marijampole":
{"region":"Marijampol\u0117","confirmed":0,"recovered":0,"deaths":0},"siauliai":
{"region":"\u0160iauliai","confirmed":3,"recovered":1,"deaths":0},"panevezys":
{"region":"Panev\u0117\u017eys","confirmed":2,"recovered":0,"deaths":0},"taurage":
{"region":"Taurag\u0117","confirmed":0,"recovered":0,"deaths":0},"telsiai":
{"region":"Tel\u0161iai","confirmed":0,"recovered":0,"deaths":0},"utena":
{"region":"Utena","confirmed":0,"recovered":0,"deaths":0},"vilnius":
{"region":"Vilnius","confirmed":59,"recovered":0,"deaths":0}}
```

and

**Comment by sagarkarira** [comment]
Source 1 is updated once a day. [https://corona-stats.online/Lithuania?minimal=true&source=1](https://corona-stats.online/Lithuania?minimal=true&source=1)

Source 2 is updated every 15 minutes. [https://corona-stats.online/Lithuania?minimal=true&source=2](https://corona-stats.online/Lithuania?minimal=true&source=2)

**Comment by sagarkarira** [comment]
I will add it this to README. 
Source 1 is JHU
Source 2 is Worldometers

**Comment by eabase** [comment]
> Source 1 is JHU

Ah, yeah, JHU is pretty bad...

BTW. Just noticed I am not able to use: `minimal` and `source` at the same time?
```bash
 curl https://corona-stats.online/Lithuania?minimal=true?source=2
```

**Comment by sagarkarira** [comment]
@eabase I made a typo. Here is the correct one.

`curl https://corona-stats.online/Lithuania?minimal=true&source=2`

**Comment by eabase** [comment]
@sagarkarira 
I just noticed that line above is still using source#1 even if you say source=2...

**Comment by sagarkarira** [comment]
@eabase [Source2](https://corona-stats.online/Lithuania?minimal=true&source=2) returns 129 cases whereas default [Source 1](https://corona-stats.online/Lithuania?minimal=true) returns 83 cases.

**Comment by eabase** [comment]
Yeah, but not when combined with the `minimal`:
```
$ curl https://corona-stats.online/Lithuania?minimal=true&source=1
[1] 439

Rank      State Confirmed  Recovered Deaths Active Mortality % Recovered % 1 Day ▲ 1 Week ▲
Lithuania Total         83         1      1     81        1.20        1.20    34 ▲     75 ▲

⚠️  Stay safe. Stay inside.

💻  Code: https://github.com/sagarkarira/coronavirus-tracker-cli
➡️  Twitter: https://twitter.com/ekrysis

⏳  Last Updated on: 22-Mar-2020 17:03 UTC

NEW UPDATE (REALTIME STATS): curl https://corona-stats.online?source=2

$ curl https://corona-stats.online/Lithuania?minimal=true&source=2
[2] 443
[1]   Done                    curl https://corona-stats.online/Lithuania?minimal=true

Rank      State Confirmed  Recovered Deaths Active Mortality % Recovered % 1 Day ▲ 1 Week ▲
Lithuania Total         83         1      1     81        1.20        1.20    34 ▲     75 ▲

⚠️  Stay safe. Stay inside.

💻  Code: https://github.com/sagarkarira/coronavirus-tracker-cli
➡️  Twitter: https://twitter.com/ekrysis

⏳  Last Updated on: 22-Mar-2020 17:03 UTC

NEW UPDATE (REALTIME STATS): curl https://corona-stats.online?source=2
```

**Comment by sagarkarira** [comment]
I think curl is removing second param. Can you put quotes around the request like this and try: 

`curl "https://corona-stats.online/Lithuania?minimal=true&source=2"`

**Comment by eabase** [comment]
@sagarkarira  Great! That did it.
