### ISSUE TITLE
Browser is output is terminal green, where are the colors?

### ISSUE THREAD

**Issue by eabase** [sagarkarira/coronavirus-tracker-cli#74]
I'm pretty sure that earlier today when I put the URL in my browser, I got all the colors. But now I only get that terrible green. 

@sagarkarira  Did you change something? (It was nice to have that in the browser as well.)

**Comment by sagarkarira** [comment]
@eabase Browser colors were always green. To implement colors in the browser would require creating a table in HTML then adding CSS for each column. 

It would take a considerable time.

**Comment by sagarkarira** [comment]
@eabase Can we close this?

**Comment by eGredius** [comment]
Hi, @sagarkarira . I want to follow by asking a color-related question. Is it possible to curl the data site in terminal with color disabled? I was actually trying to grep the numbers to create a status bar script.

Thanks for your effor on this project.
Cheers
