### ISSUE TITLE
confirmedByDay, recoveredByDay and deathsByDay arrays in json output

### ISSUE THREAD

**Issue by c0debreaker** [sagarkarira/coronavirus-tracker-cli#75]
Awesome tool!

I don't understand the numbers inside these arrays. Do each index represent something? It looks like it pertains to a single `day`. However, I'm not sure what the start date is or reference starting date.

Here's an example where input is Philippines. It's just a snippet from the complete json output

```
    "confirmedByDay": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      2,
      2,
      2,
      2,
      2,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      5,
      6,
      10,
      20,
      33,
      49,
      52,
      64,
      111,
      140,
      142,
      187,
      202,
      217,
      230,
      307,
      380
    ],
```

Thanks!

**Comment by sagarkarira** [comment]
The date is fixed so I didn't add it. It's same for all. Index[0] represents 21 Feb. 
It's being used to create a graph which is not that great but I couldn't find any better library.

`curl https://corona-stats.online/graph`
