### ISSUE TITLE
error cannot read property  'latest' of undefined

### ISSUE THREAD

**Issue by devianpctek** [sagarkarira/coronavirus-tracker-cli#81]
I'm getting the following error when trying to get the graph
`I am sorry. Something went wrong. Please report it
    Cannot read property 'latest' of undefined
  =================`

**Comment by abspython** [comment]
Same for me. https://corona-stats.online give the same error.

**Comment by MarcinWieczorek** [comment]
I thought I'd be faster. +1

**Comment by sagarkarira** [comment]
Sorry, working on it.

**Comment by MarcinWieczorek** [comment]
Is source=2 supposed to have different json schema?

**Comment by sagarkarira** [comment]
@MarcinWieczorek I have source 2 as a default one for now. When I fix JHU I will change it back. Yes it has a different schema. Historical cases and state-wise data is not available in source 2.

**Comment by MarcinWieczorek** [comment]
Yeah I understand that some data is not available, but keys such as `cases` in source 2 and `confirmed` in source 1 should be unified, right?

**Comment by sbruselario** [comment]
Same for me.

URL: https://corona-stats.online/argentina/graph
Output: _I am sorry. Something went wrong. Please report it Cannot read property 'latest' of undefined_

**Comment by sagarkarira** [comment]
I've fixed this. They have removed recovered so I am thinking of making source 2 as default source. What do you think?

**Comment by MarcinWieczorek** [comment]
I'm against changing json schema, you'd break people's scripts. Unify it and then change. I'm for the change because current source's data is quite delayed due to daily updates.

**Comment by sagarkarira** [comment]
I will try to add similar keys as in source 1 to source 2 data wherever I can. Then I would change it to default. 
JHU does not provide a real-time API and also keep changing their data uploaded to Github. They have also removed the US state-level data and now they are uploading it separately. 

Whenever I do this change I will add this to footer.

**Comment by tbandixen** [comment]
Thank you for your time and effort!

**Comment by sagarkarira** [comment]
Made source 2 as a default source. 
US state-level data was also removed from JHU. I found an API source. Will add it tomorrow.

**Comment by devianpctek** [comment]
so the error is not longer showing, closing this
