### ISSUE TITLE
Breakdown by US States is no longer available

### ISSUE THREAD

**Issue by rbledsaw3** [sagarkarira/coronavirus-tracker-cli#82]
I used to be able to get a breakdown by each US State (e.g. Illinois, Michigan, New York, etc.,) with https://corona-stats.online/US. Now it just shows the total data for the country instead.

**Comment by sagarkarira** [comment]
JHU has removed that data from their global list. They are uploading a
separate file now for US. I will add it as soon as I get time.

**Comment by rbledsaw3** [comment]
Okay. I'll close the issue then. Thanks :)

**Comment by grravity** [comment]
Was curious about this too, thank you!
