### ISSUE TITLE
502: BAD_GATEWAY

### ISSUE THREAD

**Issue by DefunctLizard** [sagarkarira/coronavirus-tracker-cli#86]
https://corona-stats.online/ is giving a 502: BAD_GATEWAY error...

Here is more information: 

```
Code: NO_STATUS_CODE_FROM_FUNCTION ID: lax1:vvwp6-1585113998131-f3be88526585
```

**Comment by sagarkarira** [comment]
It was an issue with the source API. Their server crashed yesterday. Its now fixed.

**Comment by infiltratorXYZ** [comment]
Now server crashed again:

> 502: BAD_GATEWAY Code: NO_STATUS_CODE_FROM_FUNCTION ID: arn1:4jhs7-1585235833891-1f7505896af4

btw...
Your API is very useful project. I appreciate it!

**Comment by sagarkarira** [comment]
[Source API](https://corona.lmao.ninja/) down again. Their devs are working on it.

You can use [https://corona-stats.online/?source=1](https://corona-stats.online/?source=1) till that time.

**Comment by infiltratorXYZ** [comment]
Ok, everything works for now

**Comment by sagarkarira** [comment]
They fixed it: https://github.com/NovelCOVID/API/issues/206
