### ISSUE TITLE
Site https://corona-stats.online/ down

### ISSUE THREAD

**Issue by marekkowalczyk** [sagarkarira/coronavirus-tracker-cli#90]
502: BAD_GATEWAY
Code: NO_STATUS_CODE_FROM_FUNCTION
ID: arn1:4jhs7-1585237699043-d15b89c01c8e

**Comment by sagarkarira** [comment]
https://github.com/sagarkarira/coronavirus-tracker-cli/issues/86

**Comment by sagarkarira** [comment]
They fixed it: https://github.com/NovelCOVID/API/issues/206
