### ISSUE TITLE
Data from Venezuela can't be retrieved individually

### ISSUE THREAD

**Issue by rolandoesc** [sagarkarira/coronavirus-tracker-cli#94]
Hello, 

I've been trying to fetch data from Venezuela by it's own (https://corona-stats.online/VE?format=json / https://corona-stats.online/VEN?format=json) but it doesn't provide any answer, barely data: [] and worldStats.

Is this a bug or am I doing it wrong?

**Comment by sagarkarira** [comment]
I fixed it. Check now.
